### PR TITLE
Added Support for Shortcut

### PR DESCRIPTION
**Pull request by nonunknown**
Have to say that this plugin is fucking simple and awesome at same time, I've added a shortcut command to make it even easier

### CODE REVIEW

**Comment by nonunknown** [comment]
Another thing, I will add this plugin to -> https://github.com/nonunknown/godot-powerful

**Comment by Rybadour** [comment]
Thank you!

I'll definitely want to merge this pull request but we probably want to fix a few things. When I look at the default shortcuts here: http://docs.godotengine.org/en/latest/getting_started/editor/default_key_mapping.html

I see that F9 is probably a better choice as F8 is used globally to stop the current running game.

Also which ever key we go with can we add it to the menu item so that users can self discover the key?

**Comment by nonunknown** [comment]
I think that SHIFT+C (Shift connect)

**Comment by Rybadour** [comment]
I'm a bit hesitant to use a hotkey that seems like something common but it does appear to be safe to use at the moment. I'll merge this once the hotkey is updated! Thanks for taking the time to work on this.

**Comment by nonunknown** [comment]
Added it

**Pull request merged**
