### PR TITLE
Modified file structure to more naturally integrate with projects

### PR DESCRIPTION
**Pull request by iatenine**
Moved plugin.gd and plugin.cfg to /addon/PLUGIN_NAME/ directory [where Godot expects to find them](https://godotengine.org/article/plugins)

Moved other files but accidentally created some duplicates that could be trimmed later

### CODE REVIEW

**Comment by Rybadour** [comment]
Not sure we should merge this. It's not a requirement to getting published in the at store and prevents people from using git submodules.

Why do you think this change is necessary?

**Comment by iatenine** [comment]
Not sure I follow the submodules part Is this an issue with Godot's version control tools? [Git CLI](https://git-scm.com/book/en/v2/Git-Tools-Submodules) doesn't seem to mention anything about a directory named addons at all, much less conflicts with using one

Besides that, the issue is that when installing from the asset library directly, almost nothing appears in the Godot editor but must be viewed and controlled via an external file manager

From what I can gather, this seems to be Godot's built-in filter ignoring "irrelevant" file types such as cfg when not being actively used for a plugin (the gif file also didn't appear)

So the goal is to effectively have the asset library listing work as expected: 

> Download > Install > Project Settings > Plugins > Refresh (maybe) > Enable plugin 

Seems to be the defacto standard for most plugins:
[Heightmap](https://github.com/Zylann/godot_heightmap_plugin)
[Dialogue box](https://github.com/Schweini07/Dialogbox)
[Background Loader](https://github.com/MasterPolska123/Advanced-Backgound-Loader)

And the recommended course of action by Godot themselves:
Already linked to this one but uh.... [here ya go](https://git-scm.com/book/en/v2/Git-Tools-Submodules)

**Comment by Rybadour** [comment]
Seems like it could just as easy to install a plugin into the add-ons
directory whether it contains the add-ons folder or not. Since all you
download is a zip file that you have to manually extract to the right
directory.

With git submodules you can specify that a sub directory is another repo.
If my GitHub contains the addon folder I don't see how one could use got
submodules to install it. At the moment I have the plugin installed as a
submodule at ./addons/node-connector

**Comment by iatenine** [comment]
OK, I see the disconnect here!

The idea is only a plugin.gd would be visible (at least that's all I'm getting) and the user is responsible to create a directory named addons or even addons/NodeConnections that they move it into

Alright. I have a simpler fix than this file restructuring that can clear up future confusion. Keep an eye out for a much smaller patch

**Comment by Rybadour** [comment]
Wonderful! Thanks.

**Pull request closed without merging**
